"""
streamlit_app_v2.py — PHASE 14: front-end wired to the full Azure architecture.

Differs from the earlier single-process app.py: this UI no longer runs
retrieval/rerank/generation itself. It calls the APIM-fronted Function App
(circuit_breaker_function) over HTTPS, and is responsible only for:
  - clinician session (doctor/patient selection)
  - displaying the compiled U-shaped context + generated summary
  - the HITL approval form -> sends the decision to Service Bus
  - triggering DOCX prescription generation + download after sign-off
  - a lightweight RAGAS eval panel for spot-checking a response

Run:
    streamlit run streamlit_app_v2.py
"""

from __future__ import annotations

import os

import requests
import streamlit as st

from config import get_secret
from prescription_docx import PrescriptionData, PrescriptionMedication, build_prescription_docx
from servicebus_feedback import send_hitl_feedback

APIM_BASE_URL = get_secret("APIM_BASE_URL", "https://<your-apim>.azure-api.net/clinical-rag")
APIM_SUBSCRIPTION_KEY = get_secret("APIM_SUBSCRIPTION_KEY", "")

st.set_page_config(page_title="Clinical RAG Copilot v2 — Azure AI Search Architecture", layout="wide")


def call_orchestrator(doctor_id: str, patient_id: str, question: str, disease_filter: str | None,
                       bearer_token: str) -> dict:
    headers = {
        "Authorization": f"Bearer {bearer_token}",
        "Ocp-Apim-Subscription-Key": APIM_SUBSCRIPTION_KEY,
        "Content-Type": "application/json",
    }
    payload = {"doctor_id": doctor_id, "patient_id": patient_id, "question": question}
    if disease_filter:
        payload["disease_filter"] = disease_filter

    response = requests.post(f"{APIM_BASE_URL}/query", json=payload, headers=headers, timeout=30)
    return {"status_code": response.status_code, "body": response.json()}


def main() -> None:
    st.title("🏥 Clinical RAG Copilot v2 — Azure AI Search / Parent-Child / Cross-Encoder")
    st.caption(
        "Retrieval runs through Azure AI Search (multi-tenant, parent-child chunked), reranked by a "
        "cross-encoder, deduped via Redis, generated by Azure OpenAI behind a circuit breaker, and "
        "gated by APIM JWT/RBAC — this UI is a thin client over that pipeline."
    )

    with st.sidebar:
        st.header("🔑 Session")
        bearer_token = st.text_input("Bearer token (from your Entra ID sign-in)", type="password")
        doctor_id = st.text_input("Doctor / Provider ID")
        patient_id = st.text_input("Patient ID")
        disease_filter = st.text_input("Guideline disease filter (optional)", placeholder="e.g. Type 2 Diabetes")

    question = st.text_area("Clinical question", value="Summarize this patient's current clinical status.",
                             height=80)

    if st.button("🔐 Run Pipeline", type="primary"):
        if not bearer_token or not doctor_id or not patient_id:
            st.error("Bearer token, Doctor ID, and Patient ID are all required.")
            return

        with st.spinner("Calling orchestrator (retrieve → rerank → dedup → assemble → generate → verify)..."):
            result = call_orchestrator(doctor_id, patient_id, question, disease_filter or None, bearer_token)

        if result["status_code"] == 403:
            st.error(f"⛔ ACCESS DENIED: {result['body'].get('reason', 'Unauthorized.')}")
            return
        if result["status_code"] == 503:
            st.warning(f"⚠️ Upstream degraded (circuit breaker open): {result['body']}")
            return
        if result["status_code"] != 200:
            st.error(f"Request failed ({result['status_code']}): {result['body']}")
            return

        body = result["body"]
        st.session_state.last_result = body

    if "last_result" in st.session_state:
        body = st.session_state.last_result

        with st.expander("🧩 Compiled U-Shaped Context (parent chunks, deduped)", expanded=False):
            st.code(body["compiled_context"], language="text")
            st.caption(f"SHA-256: `{body['context_sha256']}` · cache hit: {body['cache_hit']}")

        safety = body["safety_verification"]
        if not safety["passed"]:
            st.error("⚠️ DETERMINISTIC SAFETY GUARDRAIL FLAGGED THIS SUMMARY:\n\n" +
                      "\n".join(f"- {c}" for c in safety["conflicts"]))

        st.subheader("📝 Generated Summary")
        st.info(body["summary"])

        st.subheader("✅ Human-in-the-Loop Approval")
        with st.form("hitl_form"):
            decision = st.radio("Decision", ["Approve", "Reject", "Approve with edits"], horizontal=True)
            edited = st.text_area("Edited text (if approving with edits)", value=body["summary"], height=120)
            comment = st.text_area("Reviewer comment")
            submitted = st.form_submit_button("Submit decision")

            if submitted:
                event = {
                    "action": {"Approve": "HITL_APPROVED", "Reject": "HITL_REJECTED",
                               "Approve with edits": "HITL_APPROVED_WITH_EDITS"}[decision],
                    "actor_doctor_id": doctor_id,
                    "subject_patient_id": patient_id,
                    "context_sha256": body["context_sha256"],
                    "detail": {"reviewer_comment": comment,
                               "final_text": edited if decision == "Approve with edits" else body["summary"]},
                }
                queued = send_hitl_feedback(event)
                st.success("Decision queued to Service Bus." if queued else
                           "Service Bus not configured — decision logged locally only (dev mode).")
                st.session_state.hitl_final_text = event["detail"]["final_text"]
                st.session_state.hitl_comment = comment
                st.session_state.hitl_approved = decision != "Reject"

        if st.session_state.get("hitl_approved"):
            st.subheader("📄 Generate Prescription (.docx)")
            with st.form("prescription_form"):
                med_name = st.text_input("Medication name")
                dosage = st.text_input("Dosage", value="500mg")
                frequency = st.text_input("Frequency", value="Twice daily")
                duration = st.text_input("Duration", value="30 days")
                instructions = st.text_input("Instructions", value="Take with food.")
                gen_docx = st.form_submit_button("Generate Prescription Document")

                if gen_docx and med_name:
                    data = PrescriptionData(
                        patient_name=patient_id, patient_id=patient_id, patient_dob="",
                        doctor_name=doctor_id, doctor_id=doctor_id, doctor_speciality="",
                        date_issued="", diagnosis_summary=st.session_state.hitl_final_text,
                        medications=[PrescriptionMedication(med_name, dosage, frequency, duration, instructions)],
                        reviewer_comment=st.session_state.hitl_comment,
                        context_sha256=body["context_sha256"],
                    )
                    out_path = f"/tmp/prescription_{patient_id}.docx"
                    build_prescription_docx(data, out_path)
                    with open(out_path, "rb") as f:
                        st.download_button("⬇️ Download Prescription", f, file_name=os.path.basename(out_path))


if __name__ == "__main__":
    main()
